package com.notova.core.transcribe

import com.notova.core.model.Transcript
import com.notova.core.model.TranscriptSegment
import kotlinx.coroutines.delay
import javax.inject.Inject

/**
 * Placeholder [Transcriber]. Returns a fixed transcript so the Record -> Notes flow works
 * before a real Whisper model is wired in. Replace with a WhisperTranscriber later.
 */
class StubTranscriber
    @Inject
    constructor() : Transcriber {
        override suspend fun transcribe(audioPath: String): Transcript {
            // Simulate on-device inference latency.
            delay(SIMULATED_LATENCY_MS)
            val segments =
                listOf(
                    TranscriptSegment(
                        startMs = 0,
                        endMs = 4000,
                        text = "This is a placeholder transcript generated by StubTranscriber.",
                        speaker = "Speaker 1",
                    ),
                    TranscriptSegment(
                        startMs = 4000,
                        endMs = 8000,
                        text = "Wire in Whisper to replace this with real on-device transcription.",
                        speaker = "Speaker 1",
                    ),
                )
            return Transcript(
                recordingId = audioPath.substringAfterLast('/').substringBeforeLast('.'),
                language = "en",
                fullText = segments.joinToString(" ") { it.text },
                segments = segments,
            )
        }

        private companion object {
            const val SIMULATED_LATENCY_MS = 300L
        }
    }
